name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- uses: php-actions/composer@v6

    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug

    - name: Install
      # Install project
      run: make install

    - name: Run Linter
      # Run Linter
      run: make lint

    - name: Run Test
      run: make test

    - name: Test & publish code coverage
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
      uses: paambaati/codeclimate-action@v4.0.0
      # Add Code Climate secret key
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        debug: true
