name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # important!
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3

    # we may use whatever way to install phpcs, just specify the path on the next step
    # however, curl seems to be the fastest
    - name: Install PHP_CodeSniffer
      run: |
        curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        php phpcs.phar --version

    - name: Run Linter
      run: make lint

    - name: Run Test
      run: make test
